FROM php:8.2.9-fpm

ARG APP_ENV

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/bin/composer

RUN apt-get update && \
    apt-get -y install gnupg && \
    apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24 && \
    su -c "echo 'deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main' > /etc/apt/sources.list.d/git.list" && \
    apt-get update -y && apt-get install -y libpng-dev git && \
    apt-get update && apt-get install -y libpng-dev && \
    apt-get install -y libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev \
      libfreetype6-dev zip libicu-dev g++ zlib1g-dev libonig-dev libzip-dev && \
    pecl install xdebug && \
    apt-get update && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && apt-get install nodejs -y

RUN docker-php-ext-configure gd --enable-gd --with-webp --with-jpeg \
    --with-xpm --with-freetype && \
    docker-php-ext-configure intl && \
    docker-php-ext-install gd && \
    docker-php-ext-install mbstring iconv && \
    docker-php-ext-install pdo pdo_mysql && \
    docker-php-ext-install calendar && \
    docker-php-ext-install intl && \
    docker-php-ext-install zip && \
    docker-php-ext-enable pdo pdo_mysql gd mbstring iconv calendar intl zip xdebug

WORKDIR /var/www/html

COPY . .

RUN mkdir public/dist

RUN if [ "$APP_ENV" = "dev" ] ; then \
    composer install --no-scripts && npm install && npm run dev:no-watch ; else \
    composer install --no-dev --no-scripts && npm install && npm run build ; fi
