version: '3.8'

services:
  php:
    build: 
      context: ..
      dockerfile: docker/php/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_php
    container_name: ${COMPOSE_PROJECT_NAME}_php_${APP_ENV}
    volumes:
      - ..:/var/www/html
    depends_on:
      - mysql
      - mailer
  
  mysql:
    build: 
      context: ..
      dockerfile: docker/mysql/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_mysql
    container_name: ${COMPOSE_PROJECT_NAME}_mysql_${APP_ENV}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_R0OT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
  
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer_${APP_ENV}
    ports:
      - ${NGINX_PORT}:8080
    depends_on:
      - mysql
  
  mailer:
    build: 
      context: ..
      dockerfile: docker/mailer/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_mailer
    container_name: ${COMPOSE_PROJECT_NAME}_mailer_${APP_ENV}
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  nginx:
    build: 
      context: ..
      dockerfile: docker/nginx/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_${APP_ENV}
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
      - ${NGINX_MAILER_PORT}:8025
    depends_on:
      - php
      - mailer
      - mysql